[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.marketing.subscriptions"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot","marketing","subscriptions"] 
icon = "../docs/setup/resources/icon.png" 
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.marketing.subscriptions"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
